DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.PUNTOVF;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.VIAJE;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.Login_Usuario;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.CANJE;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.Devolucion;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.PREMIO;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.RECORRIDO;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.CIUDAD;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.TIPOSERVICIO;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.COMPRACLIENTE;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.COMPRA;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.BUTACA_MICRO;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.PeridoFueraDeServicio;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.MICRO;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.MARCA;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.Rol_Funcionalidad;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.Usuario_Rol;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.Funcionalidad;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.Rol;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.Usuario;
DROP TABLE LOS_VIAJEROS_DEL_ANONIMATO.NumeracionDevolucion;
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SPRegistrarLLegada
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SPMicroOcupadoEnFecha
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SPCrearViaje
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_ObtenerMontoEncomienda
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_ObtenerCodigoButaca
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_Obtener_Usuario
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_Existe_Usuario
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_EstablecerPago
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_EliminarTutorOAtutorado
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_EliminarPasajeSinCancelar
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_EliminarEncomiendaSinCancelar
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_CancelarCompraSinDevolver
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_Actualizar_Cliente
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.InsertarEncomienda
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_CalcularMonto
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.InsertarPasajeTutor
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.InsertarPasaje
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.GenerarCompra
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_TraerViajesParaComprar
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_ObtenerEncomiendasDeUnaCompra
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_ObtenerPasajesDeUnaCompra
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_KGDisponibles
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_ButacasLibres
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.EstablecerTutor
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.CantidadDiscapacitados
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_ObtenerMontoPasaje
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.PElRecorridoEstaHabilitado
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_ObtenerDatosDeRecorrido
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_ModificarRecorrido
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.insertarRecorrido
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.eliminarRecorrido
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SPexisteElRecorrido 
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_Servicios
GO	    
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_Ciudades
GO	    
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_AplicarFiltrosRecorridos
GO
drop procedure LOS_VIAJEROS_DEL_ANONIMATO.login
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_ObetenerRecorrido
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_ObtenerButacasDisponibles
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.FcalcularDiasBajaMicro
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.FcalcularPasajesCompradosEn
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.Insertar_Devolucion
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.GenerarDevolucion
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_Voucher;
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_PasajesDeVoucher
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_EncomiendasDeVoucher
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SPasignarPuntosVF
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_CanjearPremio
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.ObtenerDatosDeCompra
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.FcalcularTOP5PuntosObtenidosEn
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.ReemplazarMicro
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_MicrosDeReemplazo
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.HayMicroParaReemplazo
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_PatentesTodas
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_TieneViajesProgramados
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_DarDeBajaPorMantenimiento
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_DarDeBajaDefinitivamente
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_Patentes
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.ComprasDelMicroEnPeriodo
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.CancelarCompra
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.FTOP5MicrosVaciosDestinos
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.FTOP5PasajesCancelados
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.SP_TieneViajesProgramados_Def
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.HayMicroParaReemplazo_Def
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.ComprasDelMicroEnPeriodo_Def
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_MicrosDeReemplazo_Def
GO
DROP PROCEDURE LOS_VIAJEROS_DEL_ANONIMATO.ReemplazarMicro_Def
GO
DROP FUNCTION LOS_VIAJEROS_DEL_ANONIMATO.F_Roles
GO
DROP SCHEMA LOS_VIAJEROS_DEL_ANONIMATO
GO
